const pictures=[{name:'あめあがりの ねこ',file:'assets/kitten-rainy-day.png'},{name:'にじの パンダ',file:'assets/panda-meadow.png'},{name:'うちゅうの ペンギン',file:'assets/penguin-space.png'}];
const movesFor={easy:8,normal:28,hard:80}; const praises=['えあわせ名人！','すてき！だいせいこう！','キラキラ 100てん！','やったね！すごい！'];
let level='easy',pictureIndex=0,tiles=[],blank=8,completed=Number(localStorage.getItem('puzzleStars')||0),soundOn=true;
const puzzle=document.querySelector('#puzzle'),message=document.querySelector('#message'),stars=document.querySelector('#stars'),sparkles=document.querySelector('#sparkles');
function neighbors(i){const a=[];if(i>2)a.push(i-3);if(i<6)a.push(i+3);if(i%3)a.push(i-1);if(i%3<2)a.push(i+1);return a}
function setup(){document.querySelector('.game-card').classList.remove('complete');document.querySelector('#finishedActions').hidden=true;tiles=[0,1,2,3,4,5,6,7,8];blank=8;let last=-1;for(let n=0;n<movesFor[level];n++){let choices=neighbors(blank).filter(i=>i!==last);let pick=choices[Math.floor(Math.random()*choices.length)];[tiles[blank],tiles[pick]]=[tiles[pick],tiles[blank]];last=blank;blank=pick}if(tiles.every((x,i)=>x===i))setup();render();message.textContent='あいている ばしょの となりを おしてね'}
function render(){const pic=pictures[pictureIndex];document.querySelector('#pictureName').textContent=pic.name;puzzle.innerHTML='';tiles.forEach((piece,index)=>{const b=document.createElement('button');b.className=`tile ${piece===8?'blank':''}`;b.setAttribute('aria-label',piece===8?'あいている ばしょ':`えの ピース ${piece+1}`);if(piece!==8){const row=Math.floor(piece/3),col=piece%3;b.style.backgroundImage=`url("${pic.file}")`;b.style.backgroundPosition=`${col*50}% ${row*50}%`}b.addEventListener('click',()=>move(index));puzzle.append(b)})}
function move(index){if(!neighbors(blank).includes(index))return;if(soundOn)beep(380);[tiles[blank],tiles[index]]=[tiles[index],tiles[blank]];blank=index;render();if(tiles.every((x,i)=>x===i))win()}
function win(){completed++;localStorage.setItem('puzzleStars',completed);stars.textContent=completed;message.textContent=praises[Math.floor(Math.random()*praises.length)];document.querySelector('.game-card').classList.add('complete');document.querySelector('#finishedActions').hidden=false;if(soundOn){beep(520);setTimeout(()=>beep(720),130)}for(let i=0;i<22;i++){const s=document.createElement('span');s.className='confetti';s.textContent=['⭐','🌸','✨','💖'][i%4];s.style.left='50%';s.style.top='50%';s.style.setProperty('--x',`${(Math.random()-.5)*420}px`);s.style.setProperty('--y',`${(Math.random()-.5)*360}px`);sparkles.append(s);setTimeout(()=>s.remove(),1100)}}
function hint(){const target=neighbors(blank).find(i=>tiles[i]===blank)||neighbors(blank)[0];const el=puzzle.children[target];el.classList.add('hinting');message.textContent='ここを おしてみよう！';setTimeout(()=>el.classList.remove('hinting'),1300)}
function beep(freq){try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;g.gain.value=.04;o.connect(g).connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.11);o.stop(c.currentTime+.12)}catch{}}
document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>{level=b.dataset.level;document.querySelectorAll('[data-level]').forEach(x=>x.classList.toggle('selected',x===b));setup()}));document.querySelector('#newPicture').addEventListener('click',()=>{pictureIndex=(pictureIndex+1)%pictures.length;setup()});document.querySelector('#restartButton').addEventListener('click',setup);document.querySelector('#hintButton').addEventListener('click',hint);document.querySelector('#nextButton').addEventListener('click',()=>{pictureIndex=(pictureIndex+1)%pictures.length;setup()});document.querySelector('#soundButton').addEventListener('click',e=>{soundOn=!soundOn;e.target.textContent=soundOn?'♪':'×'});stars.textContent=completed;setup();

